baseurl = "http://localhost:2016"
languageCode = "en-us"
pygmentsuseclasses = "false"
pygmentsStyle = "native"
theme = "nova_new"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  event = "/:year/:month/:day/:slug"

[taxonomies]

[params]
  DateForm = "2 January 2006"
  
  title = "hugo + novashrm"

  # date and time
    reqdate = "2006-01-02"
    earlybirdexpiration = "2006-01-02"
    formatteddate = "friday, march 4, 2016"
    formattedtime = "5:30pm - 8:00 pm"
    formattedtype = "Total Rewards Sig"
  # events
    # fees
      feeboardmember = "0"
      feestudentmember = "0"
      feetransitionmember = "0"
      feemember = "55"
      feenonmember = "70"
    # location
      locationnameanddescription = "gannett/tegna, first amendment dining room"
      locationfulladdress = "7950 jones branch drive, mclean, va 22107"
      locationdirections = "members can now take the silver line to either the tyson’s or mclean stations. at the mclean station, guests can either take the 423 or 424 bus to the jones branch bus stop which is right in front of the gannett building. at the tyson’s station, guests can take the 424 bus."
      locationparking = "please park on level p2 (follow signs to event parking)"
    # *********ARRAYS*********
    # continuing ed
      ce = ["yes"]
      cecredits = ["1.5"]
      cecreditsapproved = ["true"]
      cecreditstype = ["general or business"] 
    # session information
      programbenefits = ["""benefits and learning objectives of this program"""]
      programdescription = ["""description"""]
      sessionsubtitle = [""]
      sessiontime = ["2016-01-02T00:00:00Z"]
      sessiontitle = ["registration/networking:"]
    # speaker
      speakername = ["first and last"]
      speakertitle = ["company title"]
      speakercompany = ["company"]
      speakeremail = ["email@mail.com"]
      speakerwebsite1 = ["website.com"]
      speakerwebsite2 = ["website.com"]
      speakerwebsite3 = ["website.com"]
      speakerwebsite4 = ["website.com"]
      speakersession = ["program, or session title"]
      speakerbio = ["""speaker's bio information"""]     
  # news & legal
    edition = "2006-01-02"
    link = ""