baseurl = "http://localhost:2016"
languageCode = "en-us"
title = "New Northern Virginia SHRM Event"
theme = "nova"

[permalinks]
  event = "/:year/:month/:slug"

[params]
  intro = true
  headline = "Hugo + Cockpit"
  description = "A boilerplate for Northern VA SHRM Articles"
  subtitle = "Event Subtitle"
  
  # agenda
    eventdate = ""
    starttime = "8:00 am"
    endtime = "10:00 am"
    registration = "8:00 am"
    announcements = "8:15 am"
    program = "8:30 am"
    wrapup = "9:45 am"
  # location
    locationName = "Gannett/TEGNA, First Amendment Dining Room"
    locationAddress = "7950 Jones Branch Drive, McLean, VA 22107"
    locationDirections = "Members can now take the Silver Line to either the Tyson’s or McLean stations. At the McLean station, guests can either take the 423 or 424 bus to the Jones Branch Bus Stop which is right in front of the Gannett building. At the Tyson’s station, guests can take the 424 bus."
    locationParking = "Please park on level P2 (follow signs to Event parking)"
  # continuing ed
    creditsApproved = "no"
    creditsApprovedBusiness = "1.5"
    creditsApprovedGeneral = "1.5"
    creditsApprovedSHRM = "1.5"
  # fees
    studentMember = "0"
    studentMemberLimit = "3"
    transitionMember = "0"
    transitionMemberLimit = "5"
    proMember = "55"
    nonMember = "70"
    earlyDeadline = "March 22, 2016" #six days before the event

  